# Generated by Django 4.0.6 on 2022-07-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('national_id', models.PositiveIntegerField(unique=True, verbose_name='ID')),
                ('mobile_number', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
