# Generated by Django 4.0.6 on 2022-07-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('national_id', models.PositiveIntegerField(unique=True, verbose_name='ID')),
                ('mobile_number', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Mobile Number')),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
        ),
    ]
