# Generated by Django 4.0.6 on 2022-07-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuer_name', models.CharField(max_length=100)),
                ('valuer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('valuer_number', models.PositiveIntegerField(blank=True, null=True)),
                ('valuer_address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
