# Generated by Django 4.0.6 on 2022-07-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Town',
                'verbose_name_plural': 'Towns',
                'db_table': 'town',
            },
        ),
    ]
