# Generated by Django 4.0.6 on 2022-07-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(default=1, max_length=100, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
