# Generated by Django 4.0.6 on 2022-07-19 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0003_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cities', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('Customer_pin', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('contact_person_number', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.BooleanField(default=False)),
                ('town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='distributors.town')),
            ],
        ),
    ]
