# Generated by Django 3.1 on 2022-07-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0005_auto_20220714_1424'),
        ('users', '0004_auto_20220714_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
